-- CreateTable
CREATE TABLE "produk" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "image1" TEXT NOT NULL,
    "image2" TEXT NOT NULL,
    "image3" TEXT NOT NULL,
    "jenis" TEXT NOT NULL,
    "kategori" TEXT NOT NULL,
    "sub1" TEXT NOT NULL DEFAULT 'no data',
    "sub2" TEXT NOT NULL DEFAULT 'no data',
    "sub3" TEXT NOT NULL DEFAULT 'no data',
    "berat" INTEGER NOT NULL,
    "size_xs" INTEGER NOT NULL,
    "size_s" INTEGER NOT NULL,
    "size_m" INTEGER NOT NULL,
    "size_l" INTEGER NOT NULL,
    "size_xl" INTEGER NOT NULL,
    "size_xxl" INTEGER NOT NULL,
    "size_xxxl" INTEGER NOT NULL,
    "harga" INTEGER NOT NULL,
    "harga_disc" INTEGER NOT NULL DEFAULT 0,
    "disc_label" TEXT NOT NULL DEFAULT 'no',
    "status" TEXT NOT NULL DEFAULT 'on sale',
    "deskripsi" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "produk_pkey" PRIMARY KEY ("id")
);
